data:
  _target_: imcapt.data.flickr.FlickrDataModule
  h5_load: ./datasets/h5/flickr30.hdf5
  captions_path: ./datasets/captions/dataset_flickr30k.json
  folder_path: ./datasets/flickr30/Images
  batch_size: 32
model:
  attention_network_size: 512
  encoder_size: 512
  decoder_size: 512
  dropout_rate: 0.5
  fine_tune_encoder: false
  feature_map_size: 16
  embedding_size: 512
  alpha_regularization: 1
trainer:
  default_root_dir: ./outputs
  accelerator: gpu
  check_val_every_n_epoch: 5
  num_sanity_val_steps: 1
  max_epochs: 50
encoder_optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
decoder_optimizer:
  _target_: torch.optim.Adam
  lr: 0.0004
