defaults:
  - data: base
  - model: base
  - trainer: base
  - lr_scheduler: reduceonplateau
  - encoder_optimizer: adam
  - decoder_optimizer: adam
  - override hydra/job_logging: disabled 


data:
  batch_size: 32